//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudHacienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProduccion
    {
        public int IdDetalleProduccion { get; set; }
        public Nullable<int> IdProduccion { get; set; }
        public double Cantidad { get; set; }
        public double PrecioVenta { get; set; }
        public Nullable<System.DateTime> FechaProduccion { get; set; }
        public double TotalVenta { get; set; }
    
        public virtual Produccion Produccion { get; set; }
    }
}
