//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudHacienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produccion()
        {
            this.DetalleProduccion = new HashSet<DetalleProduccion>();
        }
    
        public int IdProduccion { get; set; }
        public int IdProducto { get; set; }
        public string Unidad { get; set; }
        public string Turno { get; set; }
        public int EstadoFacturacion { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public Nullable<int> Despachado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProduccion> DetalleProduccion { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual MisProductos MisProductos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
